spring:
  application:
    name: doable

  datasource:
    url: jdbc:postgresql://localhost:9000/doableDB
    username: USER
    password: PASSWORD
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

jwt:
  secret-key: ogwhe9fgefbehfowhfobodnpqohzblvkdsbiea1